server:
  port: 8080
spring:
  profiles:
    active: jdbc
  application:
    name: config-server-db
  cloud:
    config:
      label: master
      server:
        jdbc:
          sql: SELECT `KEY`,`VALUE` from PROPERTIES where APPLICATION=? and PROFILE=? and LABEL=?
          order: 0
        default-label: master
  datasource:
    url: jdbc:mysql://localhost:3306/izhbg-cloud-config?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    maxActive: 20
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/